<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="27" passed="18" failed="9" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-06T12:00:09 EDT" name="crossBrowserTestingSuite" finished-at="2023-09-06T12:03:40 EDT" duration-ms="211069">
    <groups>
    </groups>
    <test started-at="2023-09-06T12:00:09 EDT" name="CHROME" finished-at="2023-09-06T12:01:10 EDT" duration-ms="61062">
      <class name="com.tekarck.testCases.TC04A_TestForgotPassword">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,boolean)[pri:0, instance:com.tekarck.testCases.TC04A_TestForgotPassword@446293d]" started-at="2023-09-06T12:00:45 EDT" name="setUp" finished-at="2023-09-06T12:00:47 EDT" duration-ms="1739" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://login.salesforce.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="forgotPwdLinkValidation(java.lang.reflect.Method)[pri:0, instance:com.tekarck.testCases.TC04A_TestForgotPassword@446293d]" started-at="2023-09-06T12:00:47 EDT" name="forgotPwdLinkValidation" finished-at="2023-09-06T12:00:47 EDT" duration-ms="657" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC04A_TestForgotPassword.forgotPwdLinkValidation(java.lang.reflect.Method) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotPwdLinkValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tekarck.testCases.TC04A_TestForgotPassword@446293d]" started-at="2023-09-06T12:00:47 EDT" name="tearDown" finished-at="2023-09-06T12:00:48 EDT" duration-ms="19" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tekarck.testCases.TC04A_TestForgotPassword -->
      <class name="com.tekarck.testCases.TC01_LoginErrorMessage">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,boolean)[pri:0, instance:com.tekarck.testCases.TC01_LoginErrorMessage@6d3a388c]" started-at="2023-09-06T12:00:10 EDT" name="setUp" finished-at="2023-09-06T12:00:13 EDT" duration-ms="3571" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://login.salesforce.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validateLoginToTheApplnWithBlankPassword(java.lang.reflect.Method)[pri:0, instance:com.tekarck.testCases.TC01_LoginErrorMessage@6d3a388c]" started-at="2023-09-06T12:00:13 EDT" name="validateLoginToTheApplnWithBlankPassword" finished-at="2023-09-06T12:00:14 EDT" duration-ms="974" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC01_LoginErrorMessage.validateLoginToTheApplnWithBlankPassword(java.lang.reflect.Method) throws java.io.IOException,org.apache.poi.openxml4j.exceptions.InvalidFormatException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginToTheApplnWithBlankPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tekarck.testCases.TC01_LoginErrorMessage@6d3a388c]" started-at="2023-09-06T12:00:14 EDT" name="tearDown" finished-at="2023-09-06T12:00:14 EDT" duration-ms="33" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tekarck.testCases.TC01_LoginErrorMessage -->
      <class name="com.tekarck.testCases.TC03_CheckRememberMe">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,boolean)[pri:0, instance:com.tekarck.testCases.TC03_CheckRememberMe@212b5695]" started-at="2023-09-06T12:00:39 EDT" name="setUp" finished-at="2023-09-06T12:00:40 EDT" duration-ms="1678" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://login.salesforce.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginAndCheckRememberMe(java.lang.reflect.Method)[pri:0, instance:com.tekarck.testCases.TC03_CheckRememberMe@212b5695]" started-at="2023-09-06T12:00:40 EDT" name="loginAndCheckRememberMe" finished-at="2023-09-06T12:00:45 EDT" duration-ms="4696" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC03_CheckRememberMe.loginAndCheckRememberMe(java.lang.reflect.Method) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAndCheckRememberMe -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tekarck.testCases.TC03_CheckRememberMe@212b5695]" started-at="2023-09-06T12:00:45 EDT" name="tearDown" finished-at="2023-09-06T12:00:45 EDT" duration-ms="22" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tekarck.testCases.TC03_CheckRememberMe -->
      <class name="com.tekarck.testCases.TC04B_InvalidUserNameAndPassword">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,boolean)[pri:0, instance:com.tekarck.testCases.TC04B_InvalidUserNameAndPassword@69997e9d]" started-at="2023-09-06T12:00:48 EDT" name="setUp" finished-at="2023-09-06T12:00:50 EDT" duration-ms="2751" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://login.salesforce.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginToAppWithInvalidCreds(java.lang.reflect.Method)[pri:0, instance:com.tekarck.testCases.TC04B_InvalidUserNameAndPassword@69997e9d]" started-at="2023-09-06T12:00:50 EDT" name="loginToAppWithInvalidCreds" finished-at="2023-09-06T12:01:04 EDT" duration-ms="13821" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC04B_InvalidUserNameAndPassword.loginToAppWithInvalidCreds(java.lang.reflect.Method) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToAppWithInvalidCreds -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tekarck.testCases.TC04B_InvalidUserNameAndPassword@69997e9d]" started-at="2023-09-06T12:01:04 EDT" name="tearDown" finished-at="2023-09-06T12:01:04 EDT" duration-ms="21" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tekarck.testCases.TC04B_InvalidUserNameAndPassword -->
      <class name="com.tekarck.testCases.TC02_ValidLoginToSalesForce">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,boolean)[pri:0, instance:com.tekarck.testCases.TC02_ValidLoginToSalesForce@3514a4c0]" started-at="2023-09-06T12:00:14 EDT" name="setUp" finished-at="2023-09-06T12:00:16 EDT" duration-ms="1789" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://login.salesforce.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String)[pri:0, instance:com.tekarck.testCases.TC02_ValidLoginToSalesForce@3514a4c0]" started-at="2023-09-06T12:00:16 EDT" name="loginToSalesForceAppUsingDataProviders" data-provider="LoginDataProvider" finished-at="2023-09-06T12:00:21 EDT" duration-ms="4885" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[anusha@tek.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Sumedh@03]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToSalesForceAppUsingDataProviders -->
        <test-method signature="loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String)[pri:0, instance:com.tekarck.testCases.TC02_ValidLoginToSalesForce@3514a4c0]" started-at="2023-09-06T12:00:21 EDT" name="loginToSalesForceAppUsingDataProviders" data-provider="LoginDataProvider" finished-at="2023-09-06T12:00:27 EDT" duration-ms="6501" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[anusha@tek.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Sumedh]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to login for User Name and password : : anusha@tek.com  Sumedh expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to login for User Name and password : : anusha@tek.com  Sumedh expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(TC02_ValidLoginToSalesForce.java:178)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToSalesForceAppUsingDataProviders -->
        <test-method signature="loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String)[pri:0, instance:com.tekarck.testCases.TC02_ValidLoginToSalesForce@3514a4c0]" started-at="2023-09-06T12:00:27 EDT" name="loginToSalesForceAppUsingDataProviders" data-provider="LoginDataProvider" finished-at="2023-09-06T12:00:33 EDT" duration-ms="5588" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[anusha@tek]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Sumedh@03]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to login for User Name and password : : anusha@tek  Sumedh@03 expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to login for User Name and password : : anusha@tek  Sumedh@03 expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(TC02_ValidLoginToSalesForce.java:178)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToSalesForceAppUsingDataProviders -->
        <test-method signature="loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String)[pri:0, instance:com.tekarck.testCases.TC02_ValidLoginToSalesForce@3514a4c0]" started-at="2023-09-06T12:00:33 EDT" name="loginToSalesForceAppUsingDataProviders" data-provider="LoginDataProvider" finished-at="2023-09-06T12:00:39 EDT" duration-ms="5649" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[anusha@t.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Anusha]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to login for User Name and password : : anusha@t.com  Anusha expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to login for User Name and password : : anusha@t.com  Anusha expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(TC02_ValidLoginToSalesForce.java:178)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToSalesForceAppUsingDataProviders -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tekarck.testCases.TC02_ValidLoginToSalesForce@3514a4c0]" started-at="2023-09-06T12:00:39 EDT" name="tearDown" finished-at="2023-09-06T12:00:39 EDT" duration-ms="19" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tekarck.testCases.TC02_ValidLoginToSalesForce -->
      <class name="com.tekarck.testCases.TC05_ValidateUserMenuDropDown">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,boolean)[pri:0, instance:com.tekarck.testCases.TC05_ValidateUserMenuDropDown@793be5ca]" started-at="2023-09-06T12:01:04 EDT" name="setUp" finished-at="2023-09-06T12:01:06 EDT" duration-ms="1759" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://login.salesforce.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validateUserMenuDropDown(java.lang.reflect.Method)[pri:0, instance:com.tekarck.testCases.TC05_ValidateUserMenuDropDown@793be5ca]" started-at="2023-09-06T12:01:06 EDT" name="validateUserMenuDropDown" finished-at="2023-09-06T12:01:10 EDT" duration-ms="4541" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC05_ValidateUserMenuDropDown.validateUserMenuDropDown(java.lang.reflect.Method) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUserMenuDropDown -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tekarck.testCases.TC05_ValidateUserMenuDropDown@793be5ca]" started-at="2023-09-06T12:01:10 EDT" name="tearDown" finished-at="2023-09-06T12:01:10 EDT" duration-ms="21" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tekarck.testCases.TC05_ValidateUserMenuDropDown -->
    </test> <!-- CHROME -->
    <test started-at="2023-09-06T12:01:11 EDT" name="EDGE" finished-at="2023-09-06T12:02:22 EDT" duration-ms="71474">
      <class name="com.tekarck.testCases.TC04A_TestForgotPassword">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,boolean)[pri:0, instance:com.tekarck.testCases.TC04A_TestForgotPassword@7133da86]" started-at="2023-09-06T12:01:54 EDT" name="setUp" finished-at="2023-09-06T12:01:57 EDT" duration-ms="3516" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://login.salesforce.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="forgotPwdLinkValidation(java.lang.reflect.Method)[pri:0, instance:com.tekarck.testCases.TC04A_TestForgotPassword@7133da86]" started-at="2023-09-06T12:01:57 EDT" name="forgotPwdLinkValidation" finished-at="2023-09-06T12:01:58 EDT" duration-ms="615" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC04A_TestForgotPassword.forgotPwdLinkValidation(java.lang.reflect.Method) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotPwdLinkValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tekarck.testCases.TC04A_TestForgotPassword@7133da86]" started-at="2023-09-06T12:01:58 EDT" name="tearDown" finished-at="2023-09-06T12:01:58 EDT" duration-ms="18" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tekarck.testCases.TC04A_TestForgotPassword -->
      <class name="com.tekarck.testCases.TC01_LoginErrorMessage">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,boolean)[pri:0, instance:com.tekarck.testCases.TC01_LoginErrorMessage@5562c41e]" started-at="2023-09-06T12:01:11 EDT" name="setUp" finished-at="2023-09-06T12:01:14 EDT" duration-ms="3388" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://login.salesforce.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validateLoginToTheApplnWithBlankPassword(java.lang.reflect.Method)[pri:0, instance:com.tekarck.testCases.TC01_LoginErrorMessage@5562c41e]" started-at="2023-09-06T12:01:14 EDT" name="validateLoginToTheApplnWithBlankPassword" finished-at="2023-09-06T12:01:15 EDT" duration-ms="763" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC01_LoginErrorMessage.validateLoginToTheApplnWithBlankPassword(java.lang.reflect.Method) throws java.io.IOException,org.apache.poi.openxml4j.exceptions.InvalidFormatException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginToTheApplnWithBlankPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tekarck.testCases.TC01_LoginErrorMessage@5562c41e]" started-at="2023-09-06T12:01:15 EDT" name="tearDown" finished-at="2023-09-06T12:01:15 EDT" duration-ms="21" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tekarck.testCases.TC01_LoginErrorMessage -->
      <class name="com.tekarck.testCases.TC03_CheckRememberMe">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,boolean)[pri:0, instance:com.tekarck.testCases.TC03_CheckRememberMe@4d0f2471]" started-at="2023-09-06T12:01:42 EDT" name="setUp" finished-at="2023-09-06T12:01:45 EDT" duration-ms="3509" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://login.salesforce.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginAndCheckRememberMe(java.lang.reflect.Method)[pri:0, instance:com.tekarck.testCases.TC03_CheckRememberMe@4d0f2471]" started-at="2023-09-06T12:01:45 EDT" name="loginAndCheckRememberMe" finished-at="2023-09-06T12:01:54 EDT" duration-ms="8485" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC03_CheckRememberMe.loginAndCheckRememberMe(java.lang.reflect.Method) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAndCheckRememberMe -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tekarck.testCases.TC03_CheckRememberMe@4d0f2471]" started-at="2023-09-06T12:01:54 EDT" name="tearDown" finished-at="2023-09-06T12:01:54 EDT" duration-ms="22" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tekarck.testCases.TC03_CheckRememberMe -->
      <class name="com.tekarck.testCases.TC04B_InvalidUserNameAndPassword">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,boolean)[pri:0, instance:com.tekarck.testCases.TC04B_InvalidUserNameAndPassword@3232a28a]" started-at="2023-09-06T12:01:58 EDT" name="setUp" finished-at="2023-09-06T12:02:01 EDT" duration-ms="3486" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://login.salesforce.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginToAppWithInvalidCreds(java.lang.reflect.Method)[pri:0, instance:com.tekarck.testCases.TC04B_InvalidUserNameAndPassword@3232a28a]" started-at="2023-09-06T12:02:01 EDT" name="loginToAppWithInvalidCreds" finished-at="2023-09-06T12:02:13 EDT" duration-ms="11563" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC04B_InvalidUserNameAndPassword.loginToAppWithInvalidCreds(java.lang.reflect.Method) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToAppWithInvalidCreds -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tekarck.testCases.TC04B_InvalidUserNameAndPassword@3232a28a]" started-at="2023-09-06T12:02:13 EDT" name="tearDown" finished-at="2023-09-06T12:02:13 EDT" duration-ms="22" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tekarck.testCases.TC04B_InvalidUserNameAndPassword -->
      <class name="com.tekarck.testCases.TC02_ValidLoginToSalesForce">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,boolean)[pri:0, instance:com.tekarck.testCases.TC02_ValidLoginToSalesForce@32ee6fee]" started-at="2023-09-06T12:01:15 EDT" name="setUp" finished-at="2023-09-06T12:01:18 EDT" duration-ms="3497" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://login.salesforce.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String)[pri:0, instance:com.tekarck.testCases.TC02_ValidLoginToSalesForce@32ee6fee]" started-at="2023-09-06T12:01:18 EDT" name="loginToSalesForceAppUsingDataProviders" data-provider="LoginDataProvider" finished-at="2023-09-06T12:01:24 EDT" duration-ms="5225" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[anusha@tek.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Sumedh@03]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToSalesForceAppUsingDataProviders -->
        <test-method signature="loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String)[pri:0, instance:com.tekarck.testCases.TC02_ValidLoginToSalesForce@32ee6fee]" started-at="2023-09-06T12:01:24 EDT" name="loginToSalesForceAppUsingDataProviders" data-provider="LoginDataProvider" finished-at="2023-09-06T12:01:30 EDT" duration-ms="6602" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[anusha@tek.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Sumedh]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to login for User Name and password : : anusha@tek.com  Sumedh expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to login for User Name and password : : anusha@tek.com  Sumedh expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(TC02_ValidLoginToSalesForce.java:178)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToSalesForceAppUsingDataProviders -->
        <test-method signature="loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String)[pri:0, instance:com.tekarck.testCases.TC02_ValidLoginToSalesForce@32ee6fee]" started-at="2023-09-06T12:01:30 EDT" name="loginToSalesForceAppUsingDataProviders" data-provider="LoginDataProvider" finished-at="2023-09-06T12:01:36 EDT" duration-ms="5575" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[anusha@tek]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Sumedh@03]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to login for User Name and password : : anusha@tek  Sumedh@03 expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to login for User Name and password : : anusha@tek  Sumedh@03 expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(TC02_ValidLoginToSalesForce.java:178)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToSalesForceAppUsingDataProviders -->
        <test-method signature="loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String)[pri:0, instance:com.tekarck.testCases.TC02_ValidLoginToSalesForce@32ee6fee]" started-at="2023-09-06T12:01:36 EDT" name="loginToSalesForceAppUsingDataProviders" data-provider="LoginDataProvider" finished-at="2023-09-06T12:01:42 EDT" duration-ms="5722" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[anusha@t.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Anusha]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to login for User Name and password : : anusha@t.com  Anusha expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to login for User Name and password : : anusha@t.com  Anusha expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(TC02_ValidLoginToSalesForce.java:178)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToSalesForceAppUsingDataProviders -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tekarck.testCases.TC02_ValidLoginToSalesForce@32ee6fee]" started-at="2023-09-06T12:01:42 EDT" name="tearDown" finished-at="2023-09-06T12:01:42 EDT" duration-ms="20" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tekarck.testCases.TC02_ValidLoginToSalesForce -->
      <class name="com.tekarck.testCases.TC05_ValidateUserMenuDropDown">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,boolean)[pri:0, instance:com.tekarck.testCases.TC05_ValidateUserMenuDropDown@73e22a3d]" started-at="2023-09-06T12:02:13 EDT" name="setUp" finished-at="2023-09-06T12:02:17 EDT" duration-ms="4393" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://login.salesforce.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validateUserMenuDropDown(java.lang.reflect.Method)[pri:0, instance:com.tekarck.testCases.TC05_ValidateUserMenuDropDown@73e22a3d]" started-at="2023-09-06T12:02:17 EDT" name="validateUserMenuDropDown" finished-at="2023-09-06T12:02:22 EDT" duration-ms="4822" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC05_ValidateUserMenuDropDown.validateUserMenuDropDown(java.lang.reflect.Method) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUserMenuDropDown -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tekarck.testCases.TC05_ValidateUserMenuDropDown@73e22a3d]" started-at="2023-09-06T12:02:22 EDT" name="tearDown" finished-at="2023-09-06T12:02:22 EDT" duration-ms="25" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tekarck.testCases.TC05_ValidateUserMenuDropDown -->
    </test> <!-- EDGE -->
    <test started-at="2023-09-06T12:02:22 EDT" name="FIREFOX" finished-at="2023-09-06T12:03:40 EDT" duration-ms="78219">
      <class name="com.tekarck.testCases.TC04A_TestForgotPassword">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,boolean)[pri:0, instance:com.tekarck.testCases.TC04A_TestForgotPassword@2b91004a]" started-at="2023-09-06T12:03:05 EDT" name="setUp" finished-at="2023-09-06T12:03:09 EDT" duration-ms="4368" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://login.salesforce.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="forgotPwdLinkValidation(java.lang.reflect.Method)[pri:0, instance:com.tekarck.testCases.TC04A_TestForgotPassword@2b91004a]" started-at="2023-09-06T12:03:09 EDT" name="forgotPwdLinkValidation" finished-at="2023-09-06T12:03:10 EDT" duration-ms="528" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC04A_TestForgotPassword.forgotPwdLinkValidation(java.lang.reflect.Method) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotPwdLinkValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tekarck.testCases.TC04A_TestForgotPassword@2b91004a]" started-at="2023-09-06T12:03:10 EDT" name="tearDown" finished-at="2023-09-06T12:03:10 EDT" duration-ms="612" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tekarck.testCases.TC04A_TestForgotPassword -->
      <class name="com.tekarck.testCases.TC01_LoginErrorMessage">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,boolean)[pri:0, instance:com.tekarck.testCases.TC01_LoginErrorMessage@7fee8714]" started-at="2023-09-06T12:02:22 EDT" name="setUp" finished-at="2023-09-06T12:02:27 EDT" duration-ms="5108" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://login.salesforce.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validateLoginToTheApplnWithBlankPassword(java.lang.reflect.Method)[pri:0, instance:com.tekarck.testCases.TC01_LoginErrorMessage@7fee8714]" started-at="2023-09-06T12:02:27 EDT" name="validateLoginToTheApplnWithBlankPassword" finished-at="2023-09-06T12:02:28 EDT" duration-ms="405" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC01_LoginErrorMessage.validateLoginToTheApplnWithBlankPassword(java.lang.reflect.Method) throws java.io.IOException,org.apache.poi.openxml4j.exceptions.InvalidFormatException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginToTheApplnWithBlankPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tekarck.testCases.TC01_LoginErrorMessage@7fee8714]" started-at="2023-09-06T12:02:28 EDT" name="tearDown" finished-at="2023-09-06T12:02:28 EDT" duration-ms="749" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tekarck.testCases.TC01_LoginErrorMessage -->
      <class name="com.tekarck.testCases.TC03_CheckRememberMe">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,boolean)[pri:0, instance:com.tekarck.testCases.TC03_CheckRememberMe@56cdfb3b]" started-at="2023-09-06T12:02:55 EDT" name="setUp" finished-at="2023-09-06T12:02:58 EDT" duration-ms="2191" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://login.salesforce.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginAndCheckRememberMe(java.lang.reflect.Method)[pri:0, instance:com.tekarck.testCases.TC03_CheckRememberMe@56cdfb3b]" started-at="2023-09-06T12:02:58 EDT" name="loginAndCheckRememberMe" finished-at="2023-09-06T12:03:04 EDT" duration-ms="6343" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC03_CheckRememberMe.loginAndCheckRememberMe(java.lang.reflect.Method) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAndCheckRememberMe -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tekarck.testCases.TC03_CheckRememberMe@56cdfb3b]" started-at="2023-09-06T12:03:04 EDT" name="tearDown" finished-at="2023-09-06T12:03:05 EDT" duration-ms="732" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tekarck.testCases.TC03_CheckRememberMe -->
      <class name="com.tekarck.testCases.TC04B_InvalidUserNameAndPassword">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,boolean)[pri:0, instance:com.tekarck.testCases.TC04B_InvalidUserNameAndPassword@20ccf40b]" started-at="2023-09-06T12:03:10 EDT" name="setUp" finished-at="2023-09-06T12:03:19 EDT" duration-ms="8723" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://login.salesforce.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginToAppWithInvalidCreds(java.lang.reflect.Method)[pri:0, instance:com.tekarck.testCases.TC04B_InvalidUserNameAndPassword@20ccf40b]" started-at="2023-09-06T12:03:19 EDT" name="loginToAppWithInvalidCreds" finished-at="2023-09-06T12:03:30 EDT" duration-ms="10868" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC04B_InvalidUserNameAndPassword.loginToAppWithInvalidCreds(java.lang.reflect.Method) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToAppWithInvalidCreds -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tekarck.testCases.TC04B_InvalidUserNameAndPassword@20ccf40b]" started-at="2023-09-06T12:03:30 EDT" name="tearDown" finished-at="2023-09-06T12:03:30 EDT" duration-ms="710" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tekarck.testCases.TC04B_InvalidUserNameAndPassword -->
      <class name="com.tekarck.testCases.TC02_ValidLoginToSalesForce">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,boolean)[pri:0, instance:com.tekarck.testCases.TC02_ValidLoginToSalesForce@4229bb3f]" started-at="2023-09-06T12:02:28 EDT" name="setUp" finished-at="2023-09-06T12:02:32 EDT" duration-ms="3327" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://login.salesforce.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String)[pri:0, instance:com.tekarck.testCases.TC02_ValidLoginToSalesForce@4229bb3f]" started-at="2023-09-06T12:02:32 EDT" name="loginToSalesForceAppUsingDataProviders" data-provider="LoginDataProvider" finished-at="2023-09-06T12:02:36 EDT" duration-ms="4220" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[anusha@tek.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Sumedh@03]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToSalesForceAppUsingDataProviders -->
        <test-method signature="loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String)[pri:0, instance:com.tekarck.testCases.TC02_ValidLoginToSalesForce@4229bb3f]" started-at="2023-09-06T12:02:36 EDT" name="loginToSalesForceAppUsingDataProviders" data-provider="LoginDataProvider" finished-at="2023-09-06T12:02:43 EDT" duration-ms="6481" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[anusha@tek.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Sumedh]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to login for User Name and password : : anusha@tek.com  Sumedh expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to login for User Name and password : : anusha@tek.com  Sumedh expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(TC02_ValidLoginToSalesForce.java:178)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToSalesForceAppUsingDataProviders -->
        <test-method signature="loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String)[pri:0, instance:com.tekarck.testCases.TC02_ValidLoginToSalesForce@4229bb3f]" started-at="2023-09-06T12:02:43 EDT" name="loginToSalesForceAppUsingDataProviders" data-provider="LoginDataProvider" finished-at="2023-09-06T12:02:48 EDT" duration-ms="5405" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[anusha@tek]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Sumedh@03]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to login for User Name and password : : anusha@tek  Sumedh@03 expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to login for User Name and password : : anusha@tek  Sumedh@03 expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(TC02_ValidLoginToSalesForce.java:178)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToSalesForceAppUsingDataProviders -->
        <test-method signature="loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String)[pri:0, instance:com.tekarck.testCases.TC02_ValidLoginToSalesForce@4229bb3f]" started-at="2023-09-06T12:02:48 EDT" name="loginToSalesForceAppUsingDataProviders" data-provider="LoginDataProvider" finished-at="2023-09-06T12:02:55 EDT" duration-ms="6640" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(java.lang.reflect.Method,java.lang.String,java.lang.String) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[anusha@t.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Anusha]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed to login for User Name and password : : anusha@t.com  Anusha expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed to login for User Name and password : : anusha@t.com  Anusha expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at com.tekarck.testCases.TC02_ValidLoginToSalesForce.loginToSalesForceAppUsingDataProviders(TC02_ValidLoginToSalesForce.java:178)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToSalesForceAppUsingDataProviders -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tekarck.testCases.TC02_ValidLoginToSalesForce@4229bb3f]" started-at="2023-09-06T12:02:55 EDT" name="tearDown" finished-at="2023-09-06T12:02:55 EDT" duration-ms="654" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tekarck.testCases.TC02_ValidLoginToSalesForce -->
      <class name="com.tekarck.testCases.TC05_ValidateUserMenuDropDown">
        <test-method is-config="true" signature="setUp(java.lang.String,java.lang.String,boolean)[pri:0, instance:com.tekarck.testCases.TC05_ValidateUserMenuDropDown@2fb3536e]" started-at="2023-09-06T12:03:30 EDT" name="setUp" finished-at="2023-09-06T12:03:33 EDT" duration-ms="2206" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://login.salesforce.com/]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validateUserMenuDropDown(java.lang.reflect.Method)[pri:0, instance:com.tekarck.testCases.TC05_ValidateUserMenuDropDown@2fb3536e]" started-at="2023-09-06T12:03:33 EDT" name="validateUserMenuDropDown" finished-at="2023-09-06T12:03:40 EDT" duration-ms="7064" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[void com.tekarck.testCases.TC05_ValidateUserMenuDropDown.validateUserMenuDropDown(java.lang.reflect.Method) throws org.apache.poi.openxml4j.exceptions.InvalidFormatException,java.io.IOException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUserMenuDropDown -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tekarck.testCases.TC05_ValidateUserMenuDropDown@2fb3536e]" started-at="2023-09-06T12:03:40 EDT" name="tearDown" finished-at="2023-09-06T12:03:40 EDT" duration-ms="708" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tekarck.testCases.TC05_ValidateUserMenuDropDown -->
    </test> <!-- FIREFOX -->
  </suite> <!-- crossBrowserTestingSuite -->
</testng-results>
